import { PrismaClient } from '../src/lib/db';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding BazaarPulse Pakistani Apparel Database...');

  // Clean existing tables
  await prisma.priceHistory.deleteMany();
  await prisma.product.deleteMany();
  await prisma.saleEvent.deleteMany();
  await prisma.scrapeLog.deleteMany();
  await prisma.brand.deleteMany();

  console.log('🧹 Existing data wiped.');

  // 1. Brands (Dynamically seeded from PAKISTANI_BRANDS_CONFIG for all 32+ Pakistani brands)
  const { PAKISTANI_BRANDS_CONFIG } = await import('../src/pipeline/brandConfigs');
  const createdBrandsMap = new Map<string, any>();

  for (const b of PAKISTANI_BRANDS_CONFIG) {
    const record = await prisma.brand.create({
      data: {
        name: b.name,
        slug: b.slug,
        logoUrl: b.logoUrl,
        websiteUrl: b.websiteUrl,
        platform: b.platform,
        productsEndpoint: b.productsEndpoint,
        saleEndpoint: b.saleEndpoint,
        isFeatured: b.isFeatured ?? false,
      },
    });
    createdBrandsMap.set(b.slug, record);
  }

  const sapphire = createdBrandsMap.get('sapphire')!;
  const outfitters = createdBrandsMap.get('outfitters')!;
  const khaadi = createdBrandsMap.get('khaadi')!;
  const jDot = createdBrandsMap.get('j-dot')!;
  const gulAhmed = createdBrandsMap.get('gul-ahmed')!;
  const nishatLinen = createdBrandsMap.get('nishat-linen')!;
  const sanaSafinaz = createdBrandsMap.get('sana-safinaz')!;
  const bachaaParty = createdBrandsMap.get('bachaa-party')!;
  const ethnic = createdBrandsMap.get('ethnic')!;
  const limelight = createdBrandsMap.get('limelight')!;

  console.log(`✅ Created ${PAKISTANI_BRANDS_CONFIG.length} Pakistani fashion & retail brands.`);

  // 2. Sales Events
  await prisma.saleEvent.createMany({
    data: [
      {
        brandId: sapphire.id,
        title: 'Sapphire Mid-Season Gala',
        description: 'Flat 50% & 30% Off on ready-to-wear, unstitched lawn, and mens eastern collection.',
        discountUpTo: 50,
        badgeText: 'Flat 50% Off',
        bannerUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop&q=80',
        saleUrl: 'https://pk.sapphireonline.com.pk/collections/special-offers',
        isActive: true,
      },
      {
        brandId: outfitters.id,
        title: 'Outfitters Streetwear Mega Drop',
        description: 'Massive clearance on winter jackets, graphic tees, cargos, and sneakers.',
        discountUpTo: 60,
        badgeText: 'Up to 60% Off',
        bannerUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=80',
        saleUrl: 'https://outfitters.com.pk/collections/sale',
        isActive: true,
      },
      {
        brandId: khaadi.id,
        title: 'Khaadi Annual Summer Clearance',
        description: 'Up to 50% Off on signature unstitched lawn, fabrics, and accessories.',
        discountUpTo: 50,
        badgeText: 'Flat 40% & 50%',
        bannerUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&auto=format&fit=crop&q=80',
        saleUrl: 'https://pk.khaadi.com/collections/sale',
        isActive: true,
      },
      {
        brandId: jDot.id,
        title: 'J. Festive Fest & Fragrance Drop',
        description: 'Special discounts on Men Kurta Shalwar, Waistcoats, and Signature Oud Fragrances.',
        discountUpTo: 40,
        badgeText: 'Up to 40% Off',
        bannerUrl: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=1200&auto=format&fit=crop&q=80',
        saleUrl: 'https://www.junaidjamshed.com/collections/promotions',
        isActive: true,
      },
      {
        brandId: gulAhmed.id,
        title: 'Ideas Grand Clearance Extravaganza',
        description: 'Flat 50% Off on 3-piece luxury lawn, bedding home linen, and Salt western apparel.',
        discountUpTo: 70,
        badgeText: 'Mega 70% Off',
        bannerUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=1200&auto=format&fit=crop&q=80',
        saleUrl: 'https://www.gulahmedshop.com/collections/sale',
        isActive: true,
      },
    ],
  });

  console.log('✅ Created active promotional sale events.');

  // 3. Products Data (Realistic catalog of 25+ rich Pakistani fashion deals)
  const productsData = [
    // Sapphire Products
    {
      brandId: sapphire.id,
      title: 'Embroidered 3-Piece Lawn Suit - Azure Bloom',
      slug: 'sapphire-embroidered-3pc-lawn-azure-bloom',
      handle: 'sapphire-3pc-azure-bloom',
      description: 'Exquisite 3-piece embroidered lawn shirt with printed chiffon dupatta and solid dyed cambric trousers.',
      category: 'Unstitched',
      subCategory: '3-Piece Lawn',
      gender: 'WOMEN',
      originalPrice: 8990,
      salePrice: 4495,
      discountPercentage: 50,
      savingsAmount: 4495,
      inStock: true,
      inventoryQuantity: 34,
      productUrl: 'https://pk.sapphireonline.com.pk/collections/special-offers',
      primaryImageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
      imageGallery: JSON.stringify([
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
      ]),
      sizesAvailable: JSON.stringify(['Unstitched']),
      fabric: 'Lawn',
      tags: 'Lawn, Embroidered, 3-Piece, Sale, Bestseller',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 8990, discount: 0, daysAgo: 14 },
        { price: 6290, discount: 30, daysAgo: 7 },
        { price: 4495, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: sapphire.id,
      title: 'Ready-to-Wear Floral Printed Jacquard Kurti',
      slug: 'sapphire-floral-printed-jacquard-kurti',
      handle: 'sapphire-jacquard-kurti',
      description: 'Straight cut printed jacquard kurti with intricate button embellishments and organza sleeve border.',
      category: 'Ready to Wear',
      subCategory: 'Stitched Kurta',
      gender: 'WOMEN',
      originalPrice: 4990,
      salePrice: 2495,
      discountPercentage: 50,
      savingsAmount: 2495,
      inStock: true,
      inventoryQuantity: 18,
      productUrl: 'https://pk.sapphireonline.com.pk/collections/special-offers',
      primaryImageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['XS', 'S', 'M', 'L', 'XL']),
      fabric: 'Jacquard',
      tags: 'Pret, Ready to Wear, Kurti, Floral, 50% Off',
      isHotDeal: true,
      isTrending: false,
      history: [
        { price: 4990, discount: 0, daysAgo: 10 },
        { price: 2495, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: sapphire.id,
      title: "Men's Egyptian Cotton Kurta - Charcoal Slate",
      slug: 'sapphire-mens-egyptian-cotton-kurta-charcoal',
      handle: 'sapphire-mens-cotton-kurta',
      description: 'Classic fit tailored kurta made from ultra-soft long staple Egyptian cotton with banded collar.',
      category: 'Kurta',
      subCategory: 'Men Kurta',
      gender: 'MEN',
      originalPrice: 5490,
      salePrice: 3290,
      discountPercentage: 40,
      savingsAmount: 2200,
      inStock: true,
      inventoryQuantity: 22,
      productUrl: 'https://pk.sapphireonline.com.pk/collections/special-offers',
      primaryImageUrl: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
      fabric: 'Cotton',
      tags: 'Men, Kurta, Egyptian Cotton, Charcoal, Eastern',
      isHotDeal: false,
      isTrending: true,
      history: [
        { price: 5490, discount: 0, daysAgo: 12 },
        { price: 3290, discount: 40, daysAgo: 0 },
      ],
    },
    {
      brandId: sapphire.id,
      title: 'Handcrafted Velvet Khussa with Zardozi Work',
      slug: 'sapphire-handcrafted-velvet-khussa-zardozi',
      handle: 'sapphire-velvet-khussa',
      description: 'Traditional Punjabi khussa crafted with premium velvet upper, memory foam cushioning and gold zardozi motif.',
      category: 'Footwear',
      subCategory: 'Handcrafted Khussa',
      gender: 'WOMEN',
      originalPrice: 3990,
      salePrice: 1995,
      discountPercentage: 50,
      savingsAmount: 1995,
      inStock: true,
      inventoryQuantity: 12,
      productUrl: 'https://pk.sapphireonline.com.pk/collections/special-offers',
      primaryImageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['36', '37', '38', '39', '40', '41']),
      fabric: 'Velvet',
      tags: 'Footwear, Khussa, Traditional, Flat 50%',
      isHotDeal: true,
      isTrending: false,
      history: [
        { price: 3990, discount: 0, daysAgo: 20 },
        { price: 1995, discount: 50, daysAgo: 0 },
      ],
    },

    // Outfitters Products
    {
      brandId: outfitters.id,
      title: 'Oversized Varsity Bomber Jacket - Tokyo Edition',
      slug: 'outfitters-oversized-varsity-bomber-jacket',
      handle: 'outfitters-varsity-bomber',
      description: 'Heavyweight wool-blend varsity jacket with faux leather sleeves, custom chenille patch artwork and snap buttons.',
      category: 'Western',
      subCategory: 'Jackets & Hoodies',
      gender: 'MEN',
      originalPrice: 9990,
      salePrice: 3990,
      discountPercentage: 60,
      savingsAmount: 6000,
      inStock: true,
      inventoryQuantity: 15,
      productUrl: 'https://outfitters.com.pk/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['S', 'M', 'L', 'XL']),
      fabric: 'Fleece',
      tags: 'Winter, Bomber Jacket, Streetwear, 60% Off, Mega Deal',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 9990, discount: 0, daysAgo: 30 },
        { price: 6990, discount: 30, daysAgo: 15 },
        { price: 3990, discount: 60, daysAgo: 0 },
      ],
    },
    {
      brandId: outfitters.id,
      title: 'Relaxed Fit Vintage Wash Cargo Jeans',
      slug: 'outfitters-relaxed-fit-vintage-wash-cargo-jeans',
      handle: 'outfitters-cargo-jeans',
      description: '100% rigid cotton denim cargo pants with 6 utility pockets and washed enzyme distress detailing.',
      category: 'Bottoms',
      subCategory: 'Denim Jeans',
      gender: 'MEN',
      originalPrice: 5990,
      salePrice: 2990,
      discountPercentage: 50,
      savingsAmount: 3000,
      inStock: true,
      inventoryQuantity: 28,
      productUrl: 'https://outfitters.com.pk/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['30', '32', '34', '36', '38']),
      fabric: 'Denim',
      tags: 'Denim, Cargo, Streetwear, 50% Off',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 5990, discount: 0, daysAgo: 14 },
        { price: 2990, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: outfitters.id,
      title: "Women's Cropped Graphic Fleece Hoodie",
      slug: 'outfitters-womens-cropped-graphic-fleece-hoodie',
      handle: 'outfitters-cropped-hoodie',
      description: 'Brushed fleece cropped hoodie with ribbed cuffs, drop shoulders, and puff typography print.',
      category: 'Western',
      subCategory: 'Jackets & Hoodies',
      gender: 'WOMEN',
      originalPrice: 4290,
      salePrice: 2145,
      discountPercentage: 50,
      savingsAmount: 2145,
      inStock: true,
      inventoryQuantity: 19,
      productUrl: 'https://outfitters.com.pk/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['XS', 'S', 'M', 'L']),
      fabric: 'Fleece',
      tags: 'Hoodie, Fleece, Cropped, Streetwear, Women',
      isHotDeal: true,
      isTrending: false,
      history: [
        { price: 4290, discount: 0, daysAgo: 10 },
        { price: 2145, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: outfitters.id,
      title: 'Juniors Colorblock Windbreaker Jacket',
      slug: 'outfitters-juniors-colorblock-windbreaker',
      handle: 'outfitters-juniors-windbreaker',
      description: 'Lightweight water-repellent jacket with breathable mesh lining, zipper closure, and hood.',
      category: 'Kids & Infants',
      subCategory: 'Kids Apparel',
      gender: 'KIDS',
      originalPrice: 3890,
      salePrice: 1945,
      discountPercentage: 50,
      savingsAmount: 1945,
      inStock: true,
      inventoryQuantity: 14,
      productUrl: 'https://outfitters.com.pk/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['6-7Y', '8-9Y', '10-11Y', '12-13Y']),
      fabric: 'Cotton',
      tags: 'Kids, Windbreaker, Juniors, 50% Off',
      isHotDeal: true,
      isTrending: false,
      history: [
        { price: 3890, discount: 0, daysAgo: 8 },
        { price: 1945, discount: 50, daysAgo: 0 },
      ],
    },

    // Khaadi Products
    {
      brandId: khaadi.id,
      title: 'Signature 3-Piece Embroidered Cambric Suit - Ruby Crimson',
      slug: 'khaadi-signature-3pc-embroidered-cambric-ruby',
      handle: 'khaadi-3pc-cambric-ruby',
      description: 'Rich cambric shirt with heavy thread embroidery, paired with digital print pure silk dupatta and dyed cambric shalwar.',
      category: 'Unstitched',
      subCategory: '3-Piece Lawn',
      gender: 'WOMEN',
      originalPrice: 9490,
      salePrice: 5690,
      discountPercentage: 40,
      savingsAmount: 3800,
      inStock: true,
      inventoryQuantity: 40,
      productUrl: 'https://pk.khaadi.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1579965342575-16428a7c8881?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['Unstitched']),
      fabric: 'Cambric',
      tags: 'Khaadi, Cambric, Embroidered, 3-Piece, Crimson',
      isHotDeal: false,
      isTrending: true,
      history: [
        { price: 9490, discount: 0, daysAgo: 20 },
        { price: 5690, discount: 40, daysAgo: 0 },
      ],
    },
    {
      brandId: khaadi.id,
      title: 'Chapter 2 Handwoven Boxy Kurta - Mustard Ochre',
      slug: 'khaadi-chapter-2-handwoven-boxy-kurta-ochre',
      handle: 'khaadi-chapter2-kurta-ochre',
      description: 'Artisanal handwoven cotton kurta with geometric block print accents and relaxed contemporary silhouette.',
      category: 'Ready to Wear',
      subCategory: 'Stitched Kurta',
      gender: 'WOMEN',
      originalPrice: 6290,
      salePrice: 3145,
      discountPercentage: 50,
      savingsAmount: 3145,
      inStock: true,
      inventoryQuantity: 16,
      productUrl: 'https://pk.khaadi.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['8', '10', '12', '14', '16']),
      fabric: 'Cotton',
      tags: 'Chapter 2, Handwoven, Artisanal, 50% Off, Ochre',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 6290, discount: 0, daysAgo: 15 },
        { price: 3145, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: khaadi.id,
      title: 'Printed Lawn 2-Piece Kurti & Trouser Co-ord Set',
      slug: 'khaadi-printed-lawn-2pc-coord-set',
      handle: 'khaadi-2pc-coord-set',
      description: 'Matching co-ord set in breathable lawn fabric featuring abstract botanical motif and loose culotte pants.',
      category: 'Ready to Wear',
      subCategory: '2-Piece Suit',
      gender: 'WOMEN',
      originalPrice: 4690,
      salePrice: 2814,
      discountPercentage: 40,
      savingsAmount: 1876,
      inStock: true,
      inventoryQuantity: 25,
      productUrl: 'https://pk.khaadi.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['XS', 'S', 'M', 'L']),
      fabric: 'Lawn',
      tags: 'Co-ord, 2-Piece, Lawn, Pret, Daily Wear',
      isHotDeal: false,
      isTrending: false,
      history: [
        { price: 4690, discount: 0, daysAgo: 7 },
        { price: 2814, discount: 40, daysAgo: 0 },
      ],
    },

    // J. (Junaid Jamshed) Products
    {
      brandId: jDot.id,
      title: "Men's Premium Wash & Wear Kameez Shalwar - Royal Navy",
      slug: 'j-dot-mens-premium-wash-and-wear-kameez-shalwar-navy',
      handle: 'j-dot-kameez-shalwar-navy',
      description: 'Classic Pakistani stitched Kameez Shalwar in crease-resistant wash & wear fabric with delicate collar embroidery.',
      category: 'Kurta',
      subCategory: 'Men Kurta',
      gender: 'MEN',
      originalPrice: 7990,
      salePrice: 4790,
      discountPercentage: 40,
      savingsAmount: 3200,
      inStock: true,
      inventoryQuantity: 30,
      productUrl: 'https://www.junaidjamshed.com/collections/promotions',
      primaryImageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['S', 'M', 'L', 'XL']),
      fabric: 'Cotton',
      tags: 'J., Kameez Shalwar, Men Eastern, Navy, Sale',
      isHotDeal: false,
      isTrending: true,
      history: [
        { price: 7990, discount: 0, daysAgo: 16 },
        { price: 4790, discount: 40, daysAgo: 0 },
      ],
    },
    {
      brandId: jDot.id,
      title: 'Traditional Jamawar Embroidered Waistcoat - Golden Beige',
      slug: 'j-dot-traditional-jamawar-embroidered-waistcoat',
      handle: 'j-dot-waistcoat-jamawar',
      description: 'Formal wedding waistcoat with intricate metallic brocade weave, mandarin collar, and gold crest buttons.',
      category: 'Western',
      subCategory: 'Men Formal',
      gender: 'MEN',
      originalPrice: 8490,
      salePrice: 4245,
      discountPercentage: 50,
      savingsAmount: 4245,
      inStock: true,
      inventoryQuantity: 12,
      productUrl: 'https://www.junaidjamshed.com/collections/promotions',
      primaryImageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['38', '40', '42', '44']),
      fabric: 'Jacquard',
      tags: 'Waistcoat, Jamawar, Wedding, 50% Off, Formal',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 8490, discount: 0, daysAgo: 25 },
        { price: 4245, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: jDot.id,
      title: 'Janisa Luxury Pour Femme Eau De Parfum (100ml)',
      slug: 'j-dot-janisa-luxury-pour-femme-perfume',
      handle: 'j-dot-janisa-perfume',
      description: 'Opulent oriental floral fragrance opening with sweet bergamot, Turkish rose, ambergris, and white musk base notes.',
      category: 'Accessories & Fragrances',
      subCategory: 'Fragrance / Attar',
      gender: 'WOMEN',
      originalPrice: 5800,
      salePrice: 3480,
      discountPercentage: 40,
      savingsAmount: 2320,
      inStock: true,
      inventoryQuantity: 50,
      productUrl: 'https://www.junaidjamshed.com/collections/promotions',
      primaryImageUrl: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['100ml']),
      fabric: 'Fragrance',
      tags: 'Perfume, Fragrance, Janisa, Eau De Parfum, Sale',
      isHotDeal: false,
      isTrending: true,
      history: [
        { price: 5800, discount: 0, daysAgo: 14 },
        { price: 3480, discount: 40, daysAgo: 0 },
      ],
    },

    // Gul Ahmed / Ideas Products
    {
      brandId: gulAhmed.id,
      title: '3-Piece Embroidered Chiffon Dupatta Lawn Suit - Marigold Bliss',
      slug: 'gul-ahmed-3pc-embroidered-chiffon-marigold',
      handle: 'gul-ahmed-marigold-3pc',
      description: 'Luxury unstitched 3-piece featuring front-embroidered lawn shirt, pure digital printed chiffon dupatta, and dyed trousers.',
      category: 'Unstitched',
      subCategory: '3-Piece Lawn',
      gender: 'WOMEN',
      originalPrice: 9990,
      salePrice: 4995,
      discountPercentage: 50,
      savingsAmount: 4995,
      inStock: true,
      inventoryQuantity: 45,
      productUrl: 'https://www.gulahmedshop.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['Unstitched']),
      fabric: 'Lawn',
      tags: 'Gul Ahmed, Ideas, Lawn, 3-Piece, Flat 50%',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 9990, discount: 0, daysAgo: 20 },
        { price: 4995, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: gulAhmed.id,
      title: 'Salt by Ideas Vintage Acid Wash Denim Jacket',
      slug: 'gul-ahmed-salt-vintage-acid-wash-denim-jacket',
      handle: 'gul-ahmed-salt-denim-jacket',
      description: 'Unisex oversized denim jacket with distressed collar, bronze metal hardware, and dual flap chest pockets.',
      category: 'Western',
      subCategory: 'Jackets & Hoodies',
      gender: 'UNISEX',
      originalPrice: 6990,
      salePrice: 2796,
      discountPercentage: 60,
      savingsAmount: 4194,
      inStock: true,
      inventoryQuantity: 18,
      productUrl: 'https://www.gulahmedshop.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['S', 'M', 'L', 'XL']),
      fabric: 'Denim',
      tags: 'Salt, Western, Denim Jacket, 60% Off, Clearance',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 6990, discount: 0, daysAgo: 30 },
        { price: 4890, discount: 30, daysAgo: 10 },
        { price: 2796, discount: 60, daysAgo: 0 },
      ],
    },

    // Nishat Linen Products
    {
      brandId: nishatLinen.id,
      title: 'Luxury Velvet Shawl 3-Piece Unstitched Winter Suit',
      slug: 'nishat-linen-luxury-velvet-shawl-3pc-suit',
      handle: 'nishat-velvet-shawl-3pc',
      description: 'Heavily embroidered khaddar shirt and trousers paired with an opulent micro-velvet digital printed shawl.',
      category: 'Winter Wear',
      subCategory: 'Winter Unstitched',
      gender: 'WOMEN',
      originalPrice: 12990,
      salePrice: 6495,
      discountPercentage: 50,
      savingsAmount: 6495,
      inStock: true,
      inventoryQuantity: 20,
      productUrl: 'https://nishatlinen.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['Unstitched']),
      fabric: 'Khaddar',
      tags: 'Nishat, Velvet Shawl, Khaddar, Winter, 50% Off',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 12990, discount: 0, daysAgo: 21 },
        { price: 6495, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: nishatLinen.id,
      title: 'Stitched Fusion Silk Tunic - Emerald Geometric',
      slug: 'nishat-linen-stitched-fusion-silk-tunic-emerald',
      handle: 'nishat-silk-tunic-emerald',
      description: 'Contemporary loose-cut pure raw silk tunic with high slit and collar pin detailing.',
      category: 'Ready to Wear',
      subCategory: 'Stitched Kurta',
      gender: 'WOMEN',
      originalPrice: 7490,
      salePrice: 3745,
      discountPercentage: 50,
      savingsAmount: 3745,
      inStock: true,
      inventoryQuantity: 15,
      productUrl: 'https://nishatlinen.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['XS', 'S', 'M', 'L']),
      fabric: 'Silk',
      tags: 'Silk, Pret, Tunic, Emerald, 50% Off',
      isHotDeal: true,
      isTrending: false,
      history: [
        { price: 7490, discount: 0, daysAgo: 14 },
        { price: 3745, discount: 50, daysAgo: 0 },
      ],
    },

    // Sana Safinaz Products
    {
      brandId: sanaSafinaz.id,
      title: 'Muzlin Luxury Printed & Embroidered 3-Piece Lawn',
      slug: 'sana-safinaz-muzlin-luxury-3pc-lawn',
      handle: 'sana-safinaz-muzlin-3pc',
      description: 'Signature Sana Safinaz Muzlin edition with gold tilla embroidery on neckline, organza borders, and chiffon dupatta.',
      category: 'Unstitched',
      subCategory: 'Luxury Unstitched',
      gender: 'WOMEN',
      originalPrice: 11490,
      salePrice: 6894,
      discountPercentage: 40,
      savingsAmount: 4596,
      inStock: true,
      inventoryQuantity: 28,
      productUrl: 'https://www.sanasafinaz.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['Unstitched']),
      fabric: 'Lawn',
      tags: 'Sana Safinaz, Muzlin, Luxury, 3-Piece, 40% Off',
      isHotDeal: false,
      isTrending: true,
      history: [
        { price: 11490, discount: 0, daysAgo: 18 },
        { price: 6894, discount: 40, daysAgo: 0 },
      ],
    },
    {
      brandId: sanaSafinaz.id,
      title: 'Mahay Stitched Floral Co-Ord Set - Pearl Ivory',
      slug: 'sana-safinaz-mahay-stitched-floral-coord-ivory',
      handle: 'sana-safinaz-mahay-coord',
      description: 'Breezy ready-to-wear kurta and flared pants set featuring delicate pastel water-color florals.',
      category: 'Ready to Wear',
      subCategory: '2-Piece Suit',
      gender: 'WOMEN',
      originalPrice: 5990,
      salePrice: 2995,
      discountPercentage: 50,
      savingsAmount: 2995,
      inStock: true,
      inventoryQuantity: 14,
      productUrl: 'https://www.sanasafinaz.com/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['S', 'M', 'L']),
      fabric: 'Lawn',
      tags: 'Mahay, Pret, Co-Ord, Flat 50%, Ivory',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 5990, discount: 0, daysAgo: 9 },
        { price: 2995, discount: 50, daysAgo: 0 },
      ],
    },

    // Bachaa Party Products
    {
      brandId: bachaaParty.id,
      title: "Baby Girls Embroidered Net Party Frock - Powder Pink",
      slug: 'bachaa-party-baby-girls-embroidered-frock-pink',
      handle: 'bachaa-party-frock-pink',
      description: 'Layered tulle party dress with sequin bodice, soft cotton inner lining, and matching hairband.',
      category: 'Kids & Infants',
      subCategory: 'Infants & Toddlers',
      gender: 'KIDS',
      originalPrice: 3490,
      salePrice: 1745,
      discountPercentage: 50,
      savingsAmount: 1745,
      inStock: true,
      inventoryQuantity: 24,
      productUrl: 'https://bachaaparty.com/collections/clearance-sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['0-3M', '3-6M', '6-12M', '1-2Y', '2-3Y']),
      fabric: 'Cotton',
      tags: 'Kids, Baby Girl, Party Dress, Frock, 50% Off',
      isHotDeal: true,
      isTrending: false,
      history: [
        { price: 3490, discount: 0, daysAgo: 14 },
        { price: 1745, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: bachaaParty.id,
      title: "Boys Dinosaur Printed Fleece Pullover & Sweatpants Set",
      slug: 'bachaa-party-boys-dino-fleece-pullover-set',
      handle: 'bachaa-party-dino-tracksuit',
      description: 'Super warm 2-piece fleece winter tracksuit with ribbed cuffs and elasticated drawstring waistband.',
      category: 'Kids & Infants',
      subCategory: 'Boys Collection',
      gender: 'KIDS',
      originalPrice: 2990,
      salePrice: 1495,
      discountPercentage: 50,
      savingsAmount: 1495,
      inStock: true,
      inventoryQuantity: 30,
      productUrl: 'https://bachaaparty.com/collections/clearance-sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['2-3Y', '3-4Y', '4-5Y', '6-7Y']),
      fabric: 'Fleece',
      tags: 'Kids, Boys, Tracksuit, Fleece, 50% Off',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 2990, discount: 0, daysAgo: 12 },
        { price: 1495, discount: 50, daysAgo: 0 },
      ],
    },

    // Ethnic Products
    {
      brandId: ethnic.id,
      title: 'Embroidered Raw Silk Peplum Kurti - Amber Gold',
      slug: 'ethnic-embroidered-raw-silk-peplum-kurti',
      handle: 'ethnic-silk-peplum-kurti',
      description: 'Modern flared peplum top embellished with hand mirror-work and gota along the neckline and hem.',
      category: 'Ready to Wear',
      subCategory: 'Stitched Kurta',
      gender: 'WOMEN',
      originalPrice: 6990,
      salePrice: 3495,
      discountPercentage: 50,
      savingsAmount: 3495,
      inStock: true,
      inventoryQuantity: 18,
      productUrl: 'https://ethnic.pk/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['XS', 'S', 'M', 'L']),
      fabric: 'Silk',
      tags: 'Ethnic, Peplum, Raw Silk, Festive, 50% Off',
      isHotDeal: true,
      isTrending: false,
      history: [
        { price: 6990, discount: 0, daysAgo: 10 },
        { price: 3495, discount: 50, daysAgo: 0 },
      ],
    },

    // Limelight Products
    {
      brandId: limelight.id,
      title: 'Printed Cambric 2-Piece Suit - Sapphire Bloom',
      slug: 'limelight-printed-cambric-2pc-suit-bloom',
      handle: 'limelight-cambric-2pc-bloom',
      description: 'Trendy 2-piece printed cambric shirt paired with straight trousers featuring contemporary geometric borders.',
      category: 'Ready to Wear',
      subCategory: '2-Piece Suit',
      gender: 'WOMEN',
      originalPrice: 3890,
      salePrice: 1945,
      discountPercentage: 50,
      savingsAmount: 1945,
      inStock: true,
      inventoryQuantity: 35,
      productUrl: 'https://www.limelight.pk/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['XS', 'S', 'M', 'L', 'XL']),
      fabric: 'Cambric',
      tags: 'Limelight, Cambric, 2-Piece, Affordable, 50% Off',
      isHotDeal: true,
      isTrending: true,
      history: [
        { price: 3890, discount: 0, daysAgo: 15 },
        { price: 1945, discount: 50, daysAgo: 0 },
      ],
    },
    {
      brandId: limelight.id,
      title: 'Quilted Crossbody Clutch Bag with Gold Chain',
      slug: 'limelight-quilted-crossbody-clutch-gold-chain',
      handle: 'limelight-crossbody-clutch',
      description: 'Structured faux leather quilted evening bag with twist-lock closure and detachable gold chain strap.',
      category: 'Accessories & Fragrances',
      subCategory: 'Bags & Clutches',
      gender: 'WOMEN',
      originalPrice: 3290,
      salePrice: 1645,
      discountPercentage: 50,
      savingsAmount: 1645,
      inStock: true,
      inventoryQuantity: 22,
      productUrl: 'https://www.limelight.pk/collections/sale',
      primaryImageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
      sizesAvailable: JSON.stringify(['One Size']),
      fabric: 'Accessories',
      tags: 'Handbag, Clutch, Accessories, 50% Off',
      isHotDeal: true,
      isTrending: false,
      history: [
        { price: 3290, discount: 0, daysAgo: 20 },
        { price: 1645, discount: 50, daysAgo: 0 },
      ],
    },
  ];

  for (const item of productsData) {
    const { history, ...productFields } = item;

    const product = await prisma.product.create({
      data: {
        ...productFields,
        currency: 'PKR',
        scrapedAt: new Date(),
      },
    });

    // Create Price History
    for (const h of history) {
      const date = new Date();
      date.setDate(date.getDate() - h.daysAgo);

      await prisma.priceHistory.create({
        data: {
          productId: product.id,
          price: h.price,
          originalPrice: product.originalPrice,
          discountPercentage: h.discount,
          recordedAt: date,
        },
      });
    }
  }

  console.log(`✅ Seeded ${productsData.length} verified Pakistani apparel deals with price history.`);

  // Update active deal count on all brands
  const allBrands = await prisma.brand.findMany();
  for (const b of allBrands) {
    const count = await prisma.product.count({
      where: { brandId: b.id, inStock: true, discountPercentage: { gt: 0 } },
    });
    await prisma.brand.update({
      where: { id: b.id },
      data: { activeDealsCount: count },
    });
  }

  // Add initial ScrapeLog
  await prisma.scrapeLog.create({
    data: {
      status: 'SUCCESS',
      itemsScraped: productsData.length + 50,
      itemsDiscounted: productsData.length,
      durationMs: 1420,
      startedAt: new Date(Date.now() - 3600000),
      completedAt: new Date(Date.now() - 3595000),
    },
  });

  console.log('🎉 BazaarPulse seeding complete!');
}

main()
  .catch((e) => {
    console.error('Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
